### ISSUE TITLE
Create an api endpoint to be used in the wows-monitor

### ISSUE THREAD

**Issue by stewieoO** [DJDaemonix/WoWS-Karma#7]
The endpoint should take multiple account ids.
GET `/gibkarma?ids=1,2,3,4` 
or
POST `/gibkarma` with a json body `[1,2,3,4]`.

It should return and array of ids+site karma 
```
[
 {
   id: 1,
   karma: 200
 },
 {
   id: 2,
   karma: 20
 }
]
```

**Comment by DJDaemonix** [comment]
Hi Stewie,

New feature/endpoint request stands approved, mostly as requested. Here are the (future) implementation details so far :

 - 2 endpoints will be created :
   - The 1st containing ``AccountID/SiteKarma`` pairs, 
   - The 2nd containing full ID/Karmas/Flairs objects, should you wish to expand your metrics collection later on.
   
 - Method of choice will be **POST** with Body parameters. This mostly being as your GET query layout requires a custom Model that's not in ASP.NET Core (to my knowledge), and the current "Query-to-Arrays" mechanisms are frankly retarded.
 
 - Endpoints will be secured via an Access Key, sent over in each request Header. That key will be proper to your use, and can be revoked in case of security breach on either side. On top of that, HTTPS as usual for most APIs.
 - No HTTP/2, courtesy of Nginx limitations.
 
 - Regarding inputs & parameters :
   - You're responsible for validation on the IDs you're sending. I'm expecting to not see arrays randomly filled with zeroes, or non-existent account IDs.
   - Be sure to not send any "hidden account" IDs. We can't process these yet, I'm afraid. 
 
For now, this should be sufficient for you to start drafting the HTTP requests. Keep me informed if there's anything more to be added, or changed.
